#!/bin/bash

# Complete ASUS laptop fan control setup script
# This script will set up custom fan control with your preferred temperature thresholds

set -e # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PWM_ENABLE="/sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/pwm1_enable"
FAN_CONTROL_SCRIPT="/usr/local/bin/fan-control.sh"
SERVICE_FILE="/etc/systemd/system/custom-fan-control.service"
LOG_FILE="/var/log/fan-control.log"

# Function to print colored output
print_status() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
  echo -e "${BLUE}[SETUP]${NC} $1"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
  print_error "This script must be run as root (use sudo)"
  exit 1
fi

print_header "ASUS Laptop Fan Control Setup"
echo "This script will:"
echo "1. Detect your thermal zones"
echo "2. Create a custom fan control script"
echo "3. Set up a systemd service for automatic startup"
echo "4. Configure safe temperature thresholds"
echo ""

# Check if PWM control is available
if [[ ! -f "$PWM_ENABLE" ]]; then
  print_error "PWM control not found at $PWM_ENABLE"
  print_error "This script is designed for ASUS laptops with asus-nb-wmi driver"
  exit 1
fi

print_status "PWM control found at $PWM_ENABLE"

# Detect thermal zones
print_header "Detecting thermal zones..."
CPU_THERMAL_ZONE=""
for zone in /sys/class/thermal/thermal_zone*/; do
  if [[ -f "$zone/type" ]]; then
    zone_type=$(cat "$zone/type" 2>/dev/null || echo "unknown")
    zone_temp=$(cat "$zone/temp" 2>/dev/null || echo "0")
    zone_temp_c=$((zone_temp / 1000))

    echo "  $(basename $zone): $zone_type (${zone_temp_c}°C)"

    # Try to identify CPU thermal zone
    if [[ "$zone_type" == *"cpu"* ]] || [[ "$zone_type" == *"x86_pkg_temp"* ]] || [[ "$zone_type" == *"coretemp"* ]]; then
      CPU_THERMAL_ZONE="$zone/temp"
      print_status "CPU thermal zone detected: $zone ($zone_type)"
    fi
  fi
done

# Fallback to thermal_zone0 if no CPU-specific zone found
if [[ -z "$CPU_THERMAL_ZONE" ]]; then
  CPU_THERMAL_ZONE="/sys/class/thermal/thermal_zone0/temp"
  print_warning "No CPU-specific thermal zone found, using thermal_zone0"
fi

# Create the fan control script
print_header "Creating fan control script..."
cat >"$FAN_CONTROL_SCRIPT" <<'EOF'
#!/bin/bash

# Custom ASUS laptop fan control script
# Auto-generated by setup script

# Configuration
PWM_ENABLE="/sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/pwm1_enable"
THERMAL_ZONE="__THERMAL_ZONE__"
LOG_FILE="/var/log/fan-control.log"

# Temperature thresholds (in Celsius) - adjust these as needed
TEMP_OFF=45      # Fan off below this temperature
TEMP_LOW=55      # Low speed fan
TEMP_MED=70      # Medium speed fan  
TEMP_HIGH=80     # High speed fan
TEMP_MAX=85      # Maximum speed fan

# Fan control modes
FAN_OFF=0        # Fan disabled
FAN_MANUAL=1     # Manual control
FAN_AUTO=2       # Automatic control

# Current state tracking
current_mode=""
last_temp=0

# Function to log messages
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

# Function to get CPU temperature
get_cpu_temp() {
    if [[ -f "$THERMAL_ZONE" ]]; then
        local temp_raw=$(cat "$THERMAL_ZONE")
        echo $((temp_raw / 1000))
    else
        echo 0
    fi
}

# Function to set fan mode
set_fan_mode() {
    local mode=$1
    local description=$2
    
    if [[ "$current_mode" != "$mode" ]]; then
        echo "$mode" > "$PWM_ENABLE" 2>/dev/null
        if [[ $? -eq 0 ]]; then
            current_mode="$mode"
            log_message "Fan mode changed to: $description (mode $mode)"
        else
            log_message "ERROR: Failed to set fan mode $mode"
        fi
    fi
}

# Function to determine fan setting based on temperature
control_fan() {
    local temp=$1
    
    # Add hysteresis (2°C buffer to prevent rapid switching)
    local hysteresis=2
    
    if [[ $temp -lt $TEMP_OFF ]]; then
        set_fan_mode $FAN_OFF "OFF (temp: ${temp}°C < ${TEMP_OFF}°C)"
    elif [[ $temp -lt $(($TEMP_LOW + $hysteresis)) ]] && [[ $last_temp -lt $TEMP_LOW ]]; then
        set_fan_mode $FAN_MANUAL "LOW (temp: ${temp}°C)"
    elif [[ $temp -lt $(($TEMP_MED + $hysteresis)) ]] && [[ $last_temp -lt $TEMP_MED ]]; then
        set_fan_mode $FAN_MANUAL "MEDIUM (temp: ${temp}°C)"
    elif [[ $temp -lt $(($TEMP_HIGH + $hysteresis)) ]] && [[ $last_temp -lt $TEMP_HIGH ]]; then
        set_fan_mode $FAN_MANUAL "HIGH (temp: ${temp}°C)"
    elif [[ $temp -ge $TEMP_MAX ]]; then
        set_fan_mode $FAN_AUTO "MAXIMUM/AUTO (temp: ${temp}°C >= ${TEMP_MAX}°C)"
    fi
}

# Function to handle cleanup on exit
cleanup() {
    log_message "Fan control script stopping - restoring automatic control"
    set_fan_mode $FAN_AUTO "AUTO (script exit)"
    exit 0
}

# Set up signal handlers
trap cleanup SIGINT SIGTERM

# Main monitoring loop
log_message "Starting custom fan control (PID: $$)"
log_message "Temperature thresholds: OFF<${TEMP_OFF}°C, LOW<${TEMP_LOW}°C, MED<${TEMP_MED}°C, HIGH<${TEMP_HIGH}°C, MAX>=${TEMP_MAX}°C"

while true; do
    temp=$(get_cpu_temp)
    
    if [[ $temp -gt 0 ]]; then
        control_fan $temp
        last_temp=$temp
        
        # Log temperature every minute or when significant change
        if [[ $(($(date +%s) % 60)) -eq 0 ]] || [[ $((temp - last_temp)) -gt 5 ]] || [[ $((last_temp - temp)) -gt 5 ]]; then
            log_message "Temperature: ${temp}°C, Fan mode: $current_mode"
        fi
    else
        log_message "ERROR: Could not read temperature"
    fi
    
    sleep 5  # Check every 5 seconds
done
EOF

# Replace the thermal zone placeholder
sed -i "s|__THERMAL_ZONE__|$CPU_THERMAL_ZONE|g" "$FAN_CONTROL_SCRIPT"

# Make script executable
chmod +x "$FAN_CONTROL_SCRIPT"
print_status "Fan control script created at $FAN_CONTROL_SCRIPT"

# Create systemd service
print_header "Creating systemd service..."
cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=Custom Fan Control Service
After=multi-user.target

[Service]
Type=simple
ExecStart=$FAN_CONTROL_SCRIPT
Restart=always
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target
EOF

print_status "Systemd service created at $SERVICE_FILE"

# Create log file with proper permissions
touch "$LOG_FILE"
chmod 644 "$LOG_FILE"

# Reload systemd and enable service
print_header "Enabling and starting service..."
systemctl daemon-reload
systemctl enable custom-fan-control.service
systemctl start custom-fan-control.service

# Check service status
if systemctl is-active --quiet custom-fan-control.service; then
  print_status "Service started successfully!"
else
  print_error "Service failed to start. Check logs with: journalctl -u custom-fan-control.service"
fi

print_header "Setup Complete!"
echo ""
echo "Your fan control is now configured with these thresholds:"
echo "  • Fan OFF: Below 45°C"
echo "  • Manual control: 45-85°C (prevents rapid cycling)"
echo "  • Automatic control: Above 85°C (for safety)"
echo ""
echo "Useful commands:"
echo "  • Check service status: systemctl status custom-fan-control.service"
echo "  • View logs: tail -f $LOG_FILE"
echo "  • Stop service: systemctl stop custom-fan-control.service"
echo "  • Start service: systemctl start custom-fan-control.service"
echo "  • Disable service: systemctl disable custom-fan-control.service"
echo ""
echo "To modify temperature thresholds, edit: $FAN_CONTROL_SCRIPT"
echo "Then restart the service: systemctl restart custom-fan-control.service"
echo ""
print_warning "Monitor your temperatures closely for the first few hours!"
echo "Current temperature: $(cat $CPU_THERMAL_ZONE 2>/dev/null | awk '{print $1/1000}')°C"
